#===================================================
# URL: 
# Description: 
# Lisence: MIT
# Author: CC
#===================================================
name: Upload latest OpenWrt to cowtransfer

on:
  push:
    branches:
      - master
    paths:
      - 'downloadlist.txt'
  watch:
    types: started

env:
  SSH_ACTIONS: false
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@master
    
    - name: Install App
      run: |
        sudo -E apt -y install wget curl
        sudo -E apt -y autoremove --purge
        sudo -E apt -y clean
    - name: Create download.sh
      run: |
        touch download.sh
        chmod +x download.sh
        cat >> download.sh <<EOF
        #!/bin/bash
        cat downloadlist.txt | while read line;
        do 
        wget \$line;
        done
        #zip -q -r downloads.zip \$PWD/*
        EOF
        mkdir downloads
        cp download.sh downloadlist.txt downloads/
    - name: Download files
      run: |
        cd downloads/
        ./download.sh
        rm download.sh
    - name: SSH connection
      uses: mxschmitt/action-tmate@v2
      if: env.SSH_ACTIONS == 'true'

    - name: Upload files to cowtransfer
      run: |
        curl -sL https://git.io/cowtransfer | sh
        chmod +x cowtransfer-uploader
        ./cowtransfer-uploader -s -p 8 downloads/ >msg.txt
    - name: send msg
      run: |
        msg=$(cat msg.txt)
        echo $msg
        url -s "http://sc.ftqq.com/$serverchan_sckey.send?text=git&desp=${msg}"
        #curl -sL https://oapi.dingtalk.com/robot/send?access_token=73a0ee6c58410d3c121695bc591ecc024d8d43ff9f873deb3f43524c086c2d6d' -H 'Content-Type: application/json -d "{\"msgtype\": \"text\",\"text\": {\"content\": \"home:Git \"}}" 
