#===================================================
# URL: 
# Description: 
# Lisence: MIT
# Author: Lucas
#===================================================
name: Upload file to cowtransfer

on:
  push:
    branches:
      - master
    paths:
      - 'downloadlist.txt'
  watch:
    types: started

env:
  SSH_ACTIONS: false
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@master
    
    #- name: Install App
    #  run: |
    #    sudo -E apt -y install wget
    #    sudo -E apt -y autoremove --purge
    #    sudo -E apt -y clean
    - name: Create download.sh
      run: |
        touch download.sh
        chmod +x download.sh
        cat >> download.sh <<EOF
        #!/bin/bash
        cat downloadlist.txt | while read line;
        do 
        wget \$line;
        echo q
        done
        #zip -q -r downloads.zip \$PWD/*
        EOF
        mkdir downloads
        cp download.sh downloadlist.txt downloads/
    - name: Download files
      run: |
        cd downloads/
        ./download.sh
        rm download.sh
    - name: SSH connection
      uses: mxschmitt/action-tmate@v2
      if: env.SSH_ACTIONS == 'true'

    - name: Upload files to cowtransfer
      run: |
        curl -sL https://git.io/cowtransfer | sh
        chmod +x cowtransfer-uploader
        ./cowtransfer-uploader -s -p 8 downloads/ >msg.txt
    - name: Send msg
      run: |
        msg=$(cat msg.txt)
        echo $msg
        wget -O /tmp/null "http://sc.ftqq.com/SCU50799T512e17d25796b887808fe66dc2914be65cd1107562261.send?text=git&desp=${msg}"
